<?php

namespace Tests\Feature;

use App\Models\Delivery;
use App\Models\Production;
use App\Models\Store;
use App\Models\User;
use App\Models\Vehicle;
use App\Models\Warehouse;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Route;
use Tests\TestCase;

/**
 * The documentation is generated by hand and the routes are generated by hand,
 * so the two drift apart the moment only one of them is edited. That already
 * happened: routes/api.php had warehouse removed from six delivery endpoints
 * while openapi.json still advertised ADMIN, WAREHOUSE, DRIVER on all of them,
 * and the new /post endpoint was live but undocumented.
 *
 * This walks the actual route table rather than a hard-coded list, so an
 * endpoint added without a spec entry fails here instead of in a front-end
 * developer's console.
 */
class ApiContractTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Roles as the routing table actually has them.
     *
     * @return array<string, array<string, array<int, string>>>
     */
    private function routeRoles(): array
    {
        $result = [];

        foreach (Route::getRoutes() as $route) {
            foreach ($route->methods() as $method) {
                if (in_array($method, ['HEAD', 'OPTIONS'], true)) {
                    continue;
                }

                $path = '/'.ltrim($route->uri(), '/');

                if (! str_starts_with($path, '/api/')) {
                    continue;
                }

                $roles = [];

                foreach ($route->gatherMiddleware() as $middleware) {
                    if (is_string($middleware) && str_starts_with($middleware, 'role:')) {
                        $roles = array_map('trim', explode(',', substr($middleware, 5)));
                    }
                }

                $result[$path][strtolower($method)] = $roles;
            }
        }

        return $result;
    }

    private function spec(): array
    {
        $path = base_path('resources/swagger/openapi.json');

        $this->assertFileExists($path, 'openapi.json is missing');

        $decoded = json_decode((string) file_get_contents($path), true);

        $this->assertIsArray($decoded, 'openapi.json is not valid JSON');

        return $decoded['paths'] ?? [];
    }

    /**
     * A live route with no spec entry is invisible to whoever reads the docs,
     * so it may as well not exist as far as this test is concerned.
     */
    public function test_every_api_route_is_documented(): void
    {
        $spec = $this->spec();
        $missing = [];

        foreach ($this->routeRoles() as $path => $operations) {
            foreach ($operations as $method => $roles) {
                if (! isset($spec[$path][$method])) {
                    $missing[] = strtoupper($method).' '.$path;
                }
            }
        }

        $this->assertSame([], $missing, 'Routes missing from resources/swagger/openapi.json');
    }

    /**
     * The other direction: a documented endpoint that no longer exists sends a
     * front-end developer to debug a 404 that is never coming back.
     */
    public function test_every_documented_endpoint_exists(): void
    {
        $routes = $this->routeRoles();
        $missing = [];

        foreach ($this->spec() as $path => $operations) {
            if (! str_starts_with($path, '/api/')) {
                continue;
            }

            foreach ($operations as $method => $operation) {
                if (! in_array(strtoupper($method), ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'], true)) {
                    continue;
                }

                if (! isset($routes[$path][strtolower($method)])) {
                    $missing[] = strtoupper($method).' '.$path;
                }
            }
        }

        $this->assertSame([], $missing, 'Endpoints in openapi.json with no matching route');
    }

    /**
     * The point of the whole file: what a role can call in the code has to be
     * what the docs say it can call.
     *
     * The comparison is against the role list the operation declares, not
     * against every role word that happens to appear in the prose. Descriptions
     * legitimately mention other roles while explaining why they are refused
     * ("BRD:421 gives warehouse the loading job, not the start"), and reading
     * those as a permission list would make the check wrong in a way that gets
     * worked around instead of fixed.
     *
     * So each operation declares its roles once in x-roles, and the three places
     * a developer reads them are each checked against that.
     */
    public function test_documented_roles_match_the_route_middleware(): void
    {
        $spec = $this->spec();
        $drift = [];

        foreach ($this->routeRoles() as $path => $operations) {
            foreach ($operations as $method => $roles) {
                $operation = $spec[$path][$method] ?? null;

                if ($operation === null || $roles === []) {
                    continue;
                }

                $expected = $this->sorted($roles);
                $declared = $this->sorted($operation['x-roles'] ?? []);

                if ($declared === []) {
                    $drift[] = strtoupper($method).' '.$path.' has no x-roles, code allows '.implode(', ', $expected);

                    continue;
                }

                if ($declared !== $expected) {
                    $drift[] = strtoupper($method).' '.$path.' code allows '.implode(', ', $expected)
                        .' but x-roles says '.implode(', ', $declared);
                }
            }
        }

        $this->assertSame([], $drift, "Role drift between routes/api.php and openapi.json:\n".implode("\n", $drift));
    }

    /**
     * The sentence a developer reads when a request comes back 403, and the
     * parentheses on the summary line, are generated from the same list. If
     * either disagrees with the route, the docs are actively misleading even
     * though x-roles is right.
     */
    public function test_forbidden_prose_matches_the_declared_roles(): void
    {
        $spec = $this->spec();
        $drift = [];

        foreach ($this->routeRoles() as $path => $operations) {
            foreach ($operations as $method => $roles) {
                $operation = $spec[$path][$method] ?? null;
                $declared = $this->sorted($operation['x-roles'] ?? []);

                if ($operation === null || $declared === []) {
                    continue;
                }

                $forbidden = $operation['responses']['403']['description'] ?? '';

                if (preg_match('/butuh ([A-Z]+(?:, [A-Z]+)*)/', $forbidden, $matches) !== 1) {
                    $drift[] = strtoupper($method).' '.$path.' 403 description does not say which roles it needs';

                    continue;
                }

                if ($this->sorted(explode(', ', $matches[1])) !== $declared) {
                    $drift[] = strtoupper($method).' '.$path.' 403 says "butuh '.$matches[1]
                        .'" while x-roles is '.implode(', ', $declared);
                }
            }
        }

        $this->assertSame([], $drift, "403 descriptions that contradict x-roles:\n".implode("\n", $drift));
    }

    /**
     * The 403 example has to name a role that is actually refused, otherwise
     * the sample response teaches the wrong thing about who is blocked.
     */
    public function test_forbidden_examples_name_a_role_that_is_actually_refused(): void
    {
        $spec = $this->spec();
        $wrong = [];

        foreach ($this->routeRoles() as $path => $operations) {
            foreach ($operations as $method => $roles) {
                $details = $spec[$path][$method]['responses']['403']['content']['application/json']['example']['details'] ?? null;

                if ($details === null || $roles === []) {
                    continue;
                }

                if (in_array($details['your_role'] ?? '', $roles, true)) {
                    $wrong[] = strtoupper($method).' '.$path.' example shows '.$details['your_role']
                        .' as refused, but that role is allowed';
                }

                if ($this->sorted(array_map('trim', explode(',', $details['required_roles'] ?? ''))) !== $this->sorted($roles)) {
                    $wrong[] = strtoupper($method).' '.$path.' example required_roles does not match the route';
                }
            }
        }

        $this->assertSame([], $wrong, "Forbidden examples that contradict the route:\n".implode("\n", $wrong));
    }

    /**
     * @param  array<int, string>  $roles
     * @return array<int, string>
     */
    private function sorted(array $roles): array
    {
        $roles = array_values(array_unique($roles));
        sort($roles);

        return $roles;
    }

    /**
     * Some fields were removed because the BRD has no place for them, and a
     * removal that only lives in a validation rule leaves the name behind in the
     * model, the column and the documentation. That is how a client ends up
     * sending a field the API silently throws away, believing it was stored.
     *
     * `collection_target` is the one that actually happened: gone from
     * validation early on, but still in the spec's request example, so it kept
     * reappearing in request bodies. Each entry here is a field the BRD does not
     * give a delivery plan, so putting one back needs the BRD to change first.
     */
    public function test_fields_absent_from_the_brd_do_not_reappear_in_the_contract(): void
    {
        $removed = [
            'collection_target' => 'BRD 2.2 asks for driver, vehicle, stores, load qty and notes only',
        ];

        $spec = json_encode($this->spec());

        foreach ($removed as $field => $why) {
            $this->assertStringNotContainsString(
                '"'.$field.'"',
                $spec,
                "{$field} is back in the spec ({$why})"
            );
        }

        // And it has to be gone from the schema too, not just the examples.
        $this->assertFalse(
            \Schema::hasColumn('deliveries', 'collection_target'),
            'deliveries still has a collection_target column'
        );

        $fillable = (new Delivery)->getFillable();
        $this->assertNotContains('collection_target', $fillable, 'collection_target is mass-assignable again');
    }

    /**
     * The mirror of the above, checked against a real response: a client that
     * still sends the field must not see it echoed back, and it must not be
     * written either. A silently ignored field is worse than a rejected one,
     * because the caller never learns the value was lost.
     */
    public function test_an_unknown_field_in_a_delivery_payload_is_not_stored(): void
    {
        $warehouse = Warehouse::factory()->create();
        Production::factory()->posted()->yielding(100)->for($warehouse)->create();

        $created = $this->actingAs(User::factory()->admin()->create(), 'sanctum')
            ->postJson('/api/deliveries', [
                'driver_id' => User::factory()->driver()->create()->id,
                'vehicle_id' => Vehicle::factory()->create()->id,
                'warehouse_id' => $warehouse->id,
                'initial_qty_loaded_ball' => 50,
                'stores' => [Store::factory()->create()->id],
                'collection_target' => 500000,
            ])
            ->assertCreated()
            ->json('data');

        $this->assertArrayNotHasKey('collection_target', $created);

        $shown = $this->actingAs(User::factory()->admin()->create(), 'sanctum')
            ->getJson('/api/deliveries/'.$created['id'])
            ->assertOk()
            ->json('data');

        $this->assertArrayNotHasKey('collection_target', $shown);
    }
}
